[generic]
debug = False
stop_on_error = True
do_backup = True
; be sure to add the dot for the backup_extension!!
backup_extension = .BCK

[CSL]
csl_path = /media/froggi/Flightsim/X-Plane 12/Resources/plugins/LiveTraffic/Resources/CSL/