[generic]
debug = False
stop_on_error = True
do_backup = True
keep_backup_files = True
keep_temp_files = False

[CSL]
; csl_path = /media/froggi/Flightsim/X-Plane 12/Resources/plugins/LiveTraffic/Resources/CSL/
; Example: cls_path = /path/to/XP12/plugins/directory/LiveTraffic/Resources/CSL
csl_path = ./CSL/