[generic]
debug = True
stop_on_error = True
do_backup = True

[csl]
; Example: cls_path = /path/to/XP12/plugins/directory/LiveTraffic/Resources/CSL
csl_path = /media/froggi/Flightsim/X-Plane 12/Resources/plugins/LiveTraffic/Resources