[generic]
stop_on_error = True

[csl]
; Examples:
; csl_path = /media/username/X-Plane 12/Resources/plugins/LiveTraffic/Resources
; csl_path = D:\Flightsimming\X-Plane 12\Resources\plugins\LiveTraffic\Resources\CSL-Aircrafts\
csl_path = X-CSL
