[csl]
; Examples:
; csl_path = /media/username/X-Plane 12/Resources/plugins/LiveTraffic/Resources
; or
; csl_path = "D:\Flightsimming\X-Plane 12\Resources\plugins\LiveTraffic\Resources\CSL-Aircrafts\"
;
; !!Attention!! Only one path entry is allowed for now. Could change in the future.
;

csl_path = "Custom_CSL"
